version: '3.7'

services:

  api_server:
    build:
        context: ./api_backend_server
        dockerfile: Dockerfile
    depends_on:
        - mongo
    image: api_server:latest
    deploy:
        replicas: 1
        restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 3
            window: 120s
    ports: 
        - "5000:5000"

  mongo:
    image: mongo:4.2-bionic
    restart: always
    volumes:
        - type: bind
          source: ./mongo_db/data/db
          target: /data/db
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
        ME_CONFIG_MONGODB_PORT: 27017
  
  mongo-express:
    image: mongo-express:0.54
    restart: always
    ports:
        - "8081:8081"
    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: example
        ME_CONFIG_MONGODB_PORT: 27017
        ME_CONFIG_MONGODB_SERVER: mongo